### ISSUE TITLE
I'm having trouble building this:

### ISSUE THREAD

**Issue by jonathancolledge** [helderlopes/MRC_creator#1]
I get this error:

Error	C1083	Cannot open include file: 'fit_encode.hpp': No such file or directory	

Can you please help?

Thanks,

Jonathan

**Comment by jonathancolledge** [comment]
In case it helps someone build this, go to Project>Properties>C/C++>General and then add the garminfitsdk directory to Additional Include Directories and Additional #using Directories

Then Preprocessor two down from General and add _CRT_SECURE_NO_WARNINGS to the Preprocessor definitions.

Then click apply and then build solution.

**Comment by helderlopes** [comment]
Hi @jonathancolledge , sorry for my late reply. 
I corrected this issue on Project Properties on my last commit (38b9d2c). The folder "garminfitsdk" had an absolute path (now it have a relative path). 
The _CRT_SECURE_NO_WARNINGS flag is used to disable remove secure warnings regarding deprecation. 
Thanks for the input
